---
- name: reload bird
  service:
    name: bird
    state: reloaded

- name: reload bird6
  service:
    name: bird6
    state: reloaded

- name: restart bird
  service:
    name: bird
    state: restarted

- name: restart bird6
  service:
    name: bird6
    state: restarted
