- name: Use template to create interface lo config file
  template:
    src: "interface_lo.j2"
    dest: "/etc/network/interfaces.d/lo.cfg"
  with_items: network_interface_lo
  when: network_interface_lo is defined

- name: Use template to create interface config files
  template:
    src: "interfaces.j2"
    dest: "/etc/network/interfaces.d/{{ item.device }}.cfg"
  with_items: network_interfaces
  when: network_interfaces is defined
