---
- name: Install bird
  apt:
    name: bird

- name: Create directories for extra config snippets
  file:
    dest: "/etc/bird/{{ item }}"
    state: directory
  with_items:
  - bird.conf.d
  - bird6.conf.d

- name: Open firewall for BGP
  template:
    src: firewall.sh
    dest: "{{ firewall_path }}/30-bird"
  when: firewall_enabled
  notify: reload firewall

- name: Create bird6.conf
  template:
    src: "bird6.conf.j2"
    dest: "/etc/bird/bird6.conf"
  when:
    - bird.router_id is defined
    - bird.routes is defined

- name: Create BGP ipv6 peering config file
  template:
    src: "peering_v6.j2"
    dest: "/etc/bird/bird6.conf.d/30_peer_{{ item.name }}.conf"
  with_items: "{{ bird.peerings }}"
  when: bird.peerings is defined
#  notify: reload bird

- name: Create functions
  template:
    src: "function.j2"
    dest: "/etc/bird/bird6.conf.d/10_function_{{ item.name }}.conf"
  with_items: "{{ bird.function_v6 }}"
  when: bird.function_v6 is defined
  notify: reload bird

- name: Create filters
  template:
    src: "filter.j2"
    dest: "/etc/bird/bird6.conf.d/20_filter_{{ item.name }}.conf"
  with_items: "{{ bird.filter_v6 }}"
  when: bird.filter_v6 is defined
  notify: reload bird

- name: Start bird
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - bird
  - bird6
