---

- name: Restart apache2 service
  set_fact:
    apache2_state: restarted
  changed_when: true
  notify: Reload apache2 service

- name: Reload apache2 service
  systemd:
    name: apache2
    daemon_reload: yes
    state: "{{ apache2_state | default('reloaded') }}"
  become: yes

- name: Restart babeld service
  set_fact:
    babeld_state: restarted
  changed_when: true
  notify: Reload babeld service

- name: Reload babeld service
  systemd:
    name: babeld
    daemon_reload: yes
    state: "{{ babeld_state | default('reloaded') }}"
  become: yes

- name: Restart dnsmasq service
  set_fact:
    dnsmasq_state: restarted
  changed_when: true
  notify: Reload dnsmasq service

- name: Reload dnsmasq service
  systemd:
    name: dnsmasq
    daemon_reload: yes
    state: "{{ dnsmasq_state | default('reloaded') }}"
  become: yes

- name: Restart alfred service
  set_fact:
    alfred_state: restarted
  changed_when: true
  notify: Reload alfred service

- name: Reload alfred service
  systemd:
    name: alfred
    daemon_reload: yes
    state: "{{ alfred_state | default('reloaded') }}"
  become: yes

- name: Restart fastd service
  set_fact:
    fastd_state: restarted
  changed_when: true
  notify: Reload fastd service

- name: Reload fastd service
  systemd:
    name: fastd
    daemon_reload: yes
    state: "{{ fastd_state | default('reloaded') }}"
  become: yes
