---

- name: Install cli tools
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - netcat-openbsd
    - tcpdump
    - nmap
    - mtr-tiny
    - iftop
    - htop
    - dstat
    - iotop
    - vim
    - screen
    - tmux
    - byobu
    - conntrack
    - bash-completion
    - psmisc
    - curl
    - mosh
    - iputils-tracepath
    - jq
    - net-tools
    - dnsutils
    - ndisc6
    - less
    - mc

- name: Set prompt (PS1)
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\e[37m\][\[\e[m\]\[\e[32m\]\u\[\e[m\]\[\e[37m\]@\[\e[m\]\[\e[31m\]{{ servername | default("\h") }}\[\e[m\]\[\e[37m\]]\[\e[m\]\[\e[37m\]:\[\e[m\]\[\e[34m\]\w\[\e[m\] \[\e[37m\]\\$\[\e[m\] "'

- name: Set Options
  lineinfile:
    path: /root/.bashrc
    line: 'export LS_OPTIONS="--color=auto"'

- name: Set dircolors
  lineinfile:
    path: /root/.bashrc
    line: 'eval "`dircolors`"'

- name: Set dr alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias dr="ip r s t 0 | grep \"default via\" && ip -6 r s t 0 | grep \"default via\""'

- name: Set traceraute alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias traceraute="traceroute"'

- name: Set cd alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias ..="cd .."'

- name: Set l alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias l="ls $LS_OPTIONS -lA"'

- name: Set rm alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias rm="rm -i"'

- name: Set cp alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias cp="cp -i"'

- name: Set mv alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias mv="mv -i"'

- name: Set ipa alias
  lineinfile:
    path: /root/.bashrc
    line: 'alias ipa="ip -c a"'

- name: Enable bash completion
  lineinfile:
    path: /root/.bashrc
    line: 'if [ -f /etc/bash_completion ]; then . /etc/bash_completion; fi'

- name: Install bin files
  copy:
    src: "{{ item }}"
    dest: "/usr/bin/"
    owner: "root"
    mode: 0755
  with_fileglob:
    - "files/bin/*"


